# MIT License
# Copyright (c) 2022 Mehdi Janbarari (@janbarari)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

site_name: Gradle Analytics Plugin
site_url: https://janbarari.github.io/gradle-analytics-plugin/
repo_name: Gradle Analytics Plugin
repo_url: https://github.com/janbarari/gradle-analytics-plugin/
site_description: A free Gradle plugin to analyze your project builds. It provides unique visual and text metrics in the HTML format.
site_author: Mehdi Janbarari

nav:
  - Overview: index.md
  - Setup: setup.md
  - Getting Report: getting-report.md
  - Changelog: changelog.md
  - Donation 🧡: donation.md
  - Privacy & Policy: privacy-policy.md
  - Request Feature: request-feature.md
  - Report Bug: report-bug.md
  - Special Thanks: special-thanks.md
  - Third party: third-party.md
  - License: license.md
  - Community: community.md
  - Social/Press: social-press.md
  - Upcoming Milestone: upcoming-milestone.md

theme:
  name: material
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  logo: img/plugin-logo.png
  favicon: img/plugin-logo.png
  features:
    - header.autohide
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

copyright: Made with 🧡 for everyone | Copyright &copy; 2022

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/janbarari
    - icon: fontawesome/brands/discord
      link: https://discord.gg/CJSeE9y8D3
