site_name: Gradle Analytics Plugin
site_url: https://janbarari.github.io/gradle-analytics-plugin/
repo_name: Gradle Analytics Plugin
repo_url: https://github.com/janbarari/gradle-analytics-plugin/
site_description: A free Gradle plugin to analyze your project builds. It provides unique visual and text metrics in the HTML format.
site_author: Mehdi Janbarari

nav:
  - Overview: index.md
  - Setup: setup.md
  - Getting Report: getting-report.md
  - Changelog: changelog.md
  - Support: support.md
  - Contribution: contribution.md
  - Privacy & Policy: privacy-policy.md
  - Request Feature: request-feature.md
  - Report Bug: report-bug.md
  - Special Thanks: special-thanks.md
  - License: license.md

theme:
  name: material
  palette:
    primary: white
  logo: img/plugin-logo.png
  favicon: img/plugin-logo.png
  features:
    - header.autohide

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

copyright: Made with 🧡 for everyone | Copyright &copy; 2022

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/janbarari