# MIT License
# Copyright (c) 2024 Mehdi Janbarari (@janbarari)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2
executor: machine
jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: build
          command: ./gradlew clean validateSourceHeaderLicense detekt assemble test --info --stacktrace
      - codecov/upload:
          file: build/reports/jacoco/test/*.xml
  publish:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: publish
          command: ./gradlew publishToGradlePortal --info --stacktrace
  deploy-docs:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: deploy-docs
          command: |
            printf "\n\n\n --------- update apt --------- \n"
            sudo apt update
            printf "\n\n\n --------- install python3 ---------- \n"
            sudo apt install python3-pip
            pip3 --version
            printf "\n\n\n --------- install git --------- \n"
            sudo apt install git
            printf "\n\n\n --------- install mkdocs -------- \n"
            pip3 install mkdocs
            mkdocs --version
            printf "\n\n\n --------- install mkdocs-material --------- \n"
            pip3 install mkdocs-material
            printf "\n\n\n --------- deploy --------- \n"
            mkdocs gh-deploy
workflows:
  build-workflow:
    jobs:
      - build
      - deploy-docs:
          filters:
            branches:
              only:
                - main
      - publish:
          filters:
            branches:
              only:
                - main
