version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2
executor: machine
jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: build
          command: ./gradlew validateSourceHeaderLicense detekt assemble test --info --stacktrace
      - codecov/upload:
          file: build/reports/jacoco/test/*.xml
workflows:
  build-workflow:
    jobs:
      - build
