[versions]
kotlin = "1.6.20"
detekt = "1.20.0-RC2"
oshi = "6.1.6"

[libraries]
oshi = { module = "com.github.oshi:oshi-core", version.ref = "oshi" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
